#!/bin/python3

import subprocess, time, os, re, numpy, requests, random, shutil, matplotlib
from Bio import SeqIO
from Bio import Entrez

#Step 1: Ask the user for the protein and taxonomic group
def user_input():
    protein_family = input("Please enter the protein family you would like to investigate") or "glucose-6-phosphatase"
    taxonomic_group = input("Please enter the taxonomic group you're interested in") or "Aves"

    while True:
        verification = input("You would like to search for {protein_family} and {taxonomic_group}. Please indiciate whether you wish to proceed with these values. y/n")
        if verification == "y" or verification == "Y":
        print("Great, let's continue")
        break
        else:
        print("Let's try again.")
    
user_input()
